### ISSUE TITLE
Container disk space keep growing!

### ISSUE THREAD

**Issue by jonahfang** [centrifugal/centrifugo-docker#3]
I use the lastest version of centrifugo-docker and following docker-compose.yml:

```
  sock_v1:
    image: registry.cn-hangzhou.aliyuncs.com/fangzx/centrifugo_1.1
    restart: unless-stopped
    container_name: hxsockserverv1
    command: centrifugo -c config.json --admin --web
    volumes:
      - ./centrifugo.json:/centrifugo/config.json
    ports:
      - "8006:8000"

  sock_dm1:
    image: registry.cn-hangzhou.aliyuncs.com/fangzx/centrifugo_1.1
    restart: unless-stopped
    container_name: hxsockserverdm1
    command: centrifugo -c config.json --admin --web
    volumes:
      - ./centrifugo.json:/centrifugo/config.json
    ports:
      - "8007:8000"
```

and my centrifugo.json:
```
{
  "secret": "{s}",
  "admin_password": "123",
  "admin_secret": "{s}",
  "log_level": "debug"
}
```

Thanks in advance!
